server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  server_tokens off;

  gzip on;
  gzip_vary on;
  gzip_min_length 512;
  gzip_types text/css application/javascript image/svg+xml application/xml text/plain;

  location / {
    try_files $uri $uri/ =404;
    add_header Cache-Control "no-cache" always;
    include /etc/nginx/security-headers.conf;
  }

  location ~* \.(css|js|webp|jpg|svg)$ {
    expires 7d;
    add_header Cache-Control "public" always;
    include /etc/nginx/security-headers.conf;
  }
}
